image: amazoncorretto:18

stages:
  - test
  - publish

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

# Runs JUnit tests
test:
  stage: test
  before_script:
    - chmod +x ./gradlew
  script:
    - ./gradlew check
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml

# Publishes package to GitLab Package Registry:
publish-package:
  stage: publish
  before_script:
    - export VERSION_NUMBER=$CI_COMMIT_TAG
    - chmod +x ./gradlew
  script:
    - ./gradlew clean publish
  only:
    - tags
