variables:
  DOCKER_TLS_CERTDIR: ""
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - publish

# Enable cache to save dependencies until gradle-wrapper properties changed:
cache:
  key:
    files:
      - gradle/wrapper/gradle-wrapper.properties
  paths:
    - .gradle/wrapper
    - .gradle/caches
  policy: pull-push

# Builds package and uploads cache
build:
  stage: build
  image: openjdk:17.0.2-jdk-slim
  before_script:
    - chmod +x ./gradlew
  script:
    - ./gradlew --build-cache assemble
  rules:
    - if: "false"

# Runs JUnit tests inside Docker container (required to have access to Docker and Docker-Compose)
test:
  stage: test
  image: $CI_REGISTRY_IMAGE:test
  services:
    - name: docker:20.10.20-dind
      alias: docker
      command: [ "--tls=false" ]
  before_script:
    - chmod +x ./gradlew
  script:
    - docker login -u REGISTRY_TOKEN -p $REGISTRY_TOKEN $CI_REGISTRY
    - export RUNNER_IP=$(hostname -I)
    - ./gradlew --build-cache test
  variables:
    DOCKER_HOST: "tcp://docker:2375"
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
  rules:
    - if: "false"

# Publishes package to GitLab Package Registry:
publish-package:
  stage: publish
  image: openjdk:17.0.2-jdk-slim
  before_script:
    - export VERSION_NUMBER=$CI_COMMIT_TAG
    - chmod +x ./gradlew
  script:
    - ./gradlew clean publish
  only:
    - tags

# Publishes KDoc to GitLab pages
publish-kdoc:
  stage: publish
  image: openjdk:17.0.2-jdk-slim
  before_script:
    #- export VERSION_NUMBER=$CI_COMMIT_TAG
    - chmod +x ./gradlew
  script:
    - ./gradlew dokkaHtml
