stages:
  - test
  - publish

# Runs JUnit tests
test:
  stage: test
  image: gradle:jdk16
  script:
    - ./gradlew check
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml

# Publishes package to GitLab Package Registry:
publish-package:
  stage: publish
  image: amazoncorretto:18
  before_script:
    - export VERSION_NUMBER=$CI_COMMIT_TAG
  script:
    - chmod +x ./gradlew
    - ./gradlew clean publish
  only:
    - tags
