image: amazoncorretto:18

stages:
  - build
  - test
  - publish

# Enable cache to save dependencies until gradle-wrapper properties changed:
cache:
  key:
    files:
      - gradle/wrapper/gradle-wrapper.properties
  paths:
    - cache/wrapper
    - cache/caches

# Builds package and uploads cache
build:
  stage: build
  before_script:
    - chmod +x ./gradlew
  script:
    - ./gradlew --build-cache --gradle-user-home cache/ assemble

# Runs JUnit tests
test:
  stage: test
  before_script:
    - chmod +x ./gradlew
  script:
    - ./gradlew check
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml

# Publishes package to GitLab Package Registry:
publish-package:
  stage: publish
  before_script:
    - export VERSION_NUMBER=$CI_COMMIT_TAG
    - chmod +x ./gradlew
  script:
    - ./gradlew clean publish
  only:
    - tags
